version: '3.4'

services:

  graphDb:
    image: arangodb
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
      ARANGODB_OVERRIDE_DETECTED_TOTAL_MEMORY: "1024000"
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  eventStore:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=None
      - EVENTSTORE_START_STANDARD_PROJECTIONS=false
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=false
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 2113:2113 
      - 1113:113
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  graphapi:
    image: ${DOCKER_REGISTRY-}graphapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - graphDb
      - eventStore
    


volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
  eventstore-volume-data:
  eventstore-volume-logs: